[package]
name = "amogus-skins-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "amogusskins"
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3.9", features = ["minwindef", "libloaderapi", "processthreadsapi", "memoryapi"] }
